"mod:regras":
  - changed-files:
      - any-glob-to-any-file: ['engine/**']
"mod:ia":
  - changed-files:
      - any-glob-to-any-file: ['ia/**']
"mod:frontend":
  - changed-files:
      - any-glob-to-any-file: ['frontend/**']
"mod:infra":
  - changed-files:
      - any-glob-to-any-file: ['.github/**']
"mod:docs":
  - changed-files:
      - any-glob-to-any-file: ['docs/**', '*.md']